# Generated by Django 5.1.4 on 2025-01-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_alter_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='is_active',
        ),
    ]
